INSERT INTO Customers (first_name, last_name, email, location) VALUES ('Wanda', 'Samudio', wsamudio0@wp.com, 'Město Albrechtice');
INSERT INTO Customers (first_name, last_name, email, location) VALUES ('Yard', 'Baptiste', ybaptiste1@hostgator.com, 'Outeiro Seco');
INSERT INTO Customers (first_name, last_name, email, location) VALUES ('Gae', 'Bradbrook', gbradbrook2@freewebs.com, 'Carlos Casares');
INSERT INTO Customers (first_name, last_name, email, location) VALUES ('Shoshana', 'Okill', sokill3@deviantart.com, 'Jiangcun');
INSERT INTO Customers (first_name, last_name, email, location) VALUES ('Minne', 'Canete', mcanete4@mlb.com, 'Mboursou Léré');
INSERT INTO Customers (first_name, last_name, email, location) VALUES ('Estell', 'Illston', eillston5@joomla.org, 'Barat');
INSERT INTO Customers (first_name, last_name, email, location) VALUES ('Minta', 'Deeson', mdeeson6@rakuten.co.jp, 'Meixi');
INSERT INTO Customers (first_name, last_name, email, location) VALUES ('Shepherd', 'Cotelard', scotelard7@sina.com.cn, 'Bentengjawa');
INSERT INTO Customers (first_name, last_name, email, location) VALUES ('Katey', 'Lackie', klackie8@noaa.gov, 'Ambatolampy');
INSERT INTO Customers (first_name, last_name, email, location) VALUES ('Alick', 'Ackrill', aackrill9@shinystat.com, 'Agpangi');
INSERT INTO Customers (first_name, last_name, email, location) VALUES ('Bari', 'Gildroy', bgildroya@epa.gov, 'Omoku');
INSERT INTO Customers (first_name, last_name, email, location) VALUES ('Sissie', 'Fakes', sfakesb@tripadvisor.com, 'Pulo');
INSERT INTO Customers (first_name, last_name, email, location) VALUES ('Arleyne', 'Rosier', arosierc@tinyurl.com, 'Igarapé');
INSERT INTO Customers (first_name, last_name, email, location) VALUES ('Selia', 'Kidwell', skidwelld@mail.ru, 'Aksu');
INSERT INTO Customers (first_name, last_name, email, location) VALUES ('Buddie', 'Agates', bagatese@sina.com.cn, 'Udi');
INSERT INTO Customers (first_name, last_name, email, location) VALUES ('Braden', 'Jiles', bjilesf@icq.com, 'Lovran');
INSERT INTO Customers (first_name, last_name, email, location) VALUES ('Nicol', 'Lanchberry', nlanchberryg@google.com.hk, 'Conima');
INSERT INTO Customers (first_name, last_name, email, location) VALUES ('Jeanelle', 'Tindley', jtindleyh@desdev.cn, 'Křenovice');
INSERT INTO Customers (first_name, last_name, email, location) VALUES ('Sarita', 'Darrington', sdarringtoni@addthis.com, 'Barrie');
INSERT INTO Customers (first_name, last_name, email, location) VALUES ('Archaimbaud', 'Simek', asimekj@umn.edu, 'Dallas');
INSERT INTO Customers (first_name, last_name, email, location) VALUES ('Lexis', 'Orniz', lornizk@woothemes.com, 'Assiniboia');
INSERT INTO Customers (first_name, last_name, email, location) VALUES ('Foster', 'Lente', flentel@oaic.gov.au, 'Pogonsili');
INSERT INTO Customers (first_name, last_name, email, location) VALUES ('Chuck', 'Canepe', ccanepem@wikipedia.org, 'Lizhuangzi');
INSERT INTO Customers (first_name, last_name, email, location) VALUES ('Berni', 'Simunek', bsimunekn@sohu.com, 'Khon Kaen');
INSERT INTO Customers (first_name, last_name, email, location) VALUES ('Templeton', 'Ragborne', tragborneo@mapquest.com, 'Viline');
INSERT INTO Customers (first_name, last_name, email, location) VALUES ('Sim', 'Nafzger', snafzgerp@wordpress.org, 'Łobodno');
INSERT INTO Customers (first_name, last_name, email, location) VALUES ('Henrie', 'Castiblanco', hcastiblancoq@omniture.com, 'Ya’erya');
INSERT INTO Customers (first_name, last_name, email, location) VALUES ('Hewe', 'Heis', hheisr@surveymonkey.com, 'Kostopil’');
INSERT INTO Customers (first_name, last_name, email, location) VALUES ('Fraze', 'Sauvan', fsauvans@ted.com, 'Omutninsk');
INSERT INTO Customers (first_name, last_name, email, location) VALUES ('Kaitlynn', 'Yurkin', kyurkint@rambler.ru, 'Geneng');
INSERT INTO Customers (first_name, last_name, email, location) VALUES ('Matti', 'Heigho', mheighou@time.com, 'Zykovo');
INSERT INTO Customers (first_name, last_name, email, location) VALUES ('Milicent', 'Swede', mswedev@state.gov, 'Birmingham');
INSERT INTO Customers (first_name, last_name, email, location) VALUES ('Malia', 'Goldwater', mgoldwaterw@fotki.com, 'Atakpamé');
INSERT INTO Customers (first_name, last_name, email, location) VALUES ('Piotr', 'Shills', pshillsx@altervista.org, 'Barengkok');
INSERT INTO Customers (first_name, last_name, email, location) VALUES ('Ingemar', 'Firmin', ifirminy@chronoengine.com, 'Florencia');
INSERT INTO Customers (first_name, last_name, email, location) VALUES ('Gwenneth', 'Pfaffe', gpfaffez@state.gov, 'North York');
INSERT INTO Customers (first_name, last_name, email, location) VALUES ('Keriann', 'Sexty', ksexty10@zdnet.com, 'Al Bāţinah');
INSERT INTO Customers (first_name, last_name, email, location) VALUES ('Tawsha', 'Skillitt', tskillitt11@reference.com, 'Kosikha');
INSERT INTO Customers (first_name, last_name, email, location) VALUES ('Cosette', 'Etteridge', cetteridge12@qq.com, 'Shahr-e Şafā');
INSERT INTO Customers (first_name, last_name, email, location) VALUES ('Adrien', 'Gatesman', agatesman13@bloglovin.com, 'Shuyuan');
INSERT INTO Customers (first_name, last_name, email, location) VALUES ('Fannie', 'Ladbury', fladbury14@imageshack.us, 'Jiling');
INSERT INTO Customers (first_name, last_name, email, location) VALUES ('Vassili', 'Sturmey', vsturmey15@phpbb.com, 'Vnorovy');
INSERT INTO Customers (first_name, last_name, email, location) VALUES ('Rolph', 'Layus', rlayus16@ftc.gov, 'Fangxi');
INSERT INTO Customers (first_name, last_name, email, location) VALUES ('Skell', 'Packham', spackham17@gnu.org, 'Králův Dvůr');
INSERT INTO Customers (first_name, last_name, email, location) VALUES ('Kelli', 'Font', kfont18@tmall.com, 'Huangdu');
INSERT INTO Customers (first_name, last_name, email, location) VALUES ('Phyllis', 'Wiggam', pwiggam19@jiathis.com, 'Roriz');
INSERT INTO Customers (first_name, last_name, email, location) VALUES ('Halsy', 'Colquite', hcolquite1a@prlog.org, 'Yuanqiao');
INSERT INTO Customers (first_name, last_name, email, location) VALUES ('Dianemarie', 'Arnaud', darnaud1b@delicious.com, 'Chita');
INSERT INTO Customers (first_name, last_name, email, location) VALUES ('Sterne', 'Looker', slooker1c@ed.gov, 'Ntobo');
INSERT INTO Customers (first_name, last_name, email, location) VALUES ('Allegra', 'Prestwich', aprestwich1d@aboutads.info, 'Leles');
